name: sample_flutter_architecture
description: A Flutter app with Riverpod + Hooks layered architecture.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.16.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  hooks_riverpod: ^2.6.1
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  dio: ^5.7.0
  retrofit: ^4.4.1
  go_router: ^14.6.2
  shared_preferences: ^2.3.4
  objectbox: ^4.0.3
  objectbox_flutter_libs: ^4.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  retrofit_generator: ^9.1.5
  riverpod_generator: ^2.6.2
  objectbox_generator: ^4.0.3
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
  assets:
    - assets/
