name: sample_flutter_architecture
description: A Flutter app with Riverpod + Hooks layered architecture.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.11.0 <4.0.0'
  flutter: '>=3.41.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.3+1
  hooks_riverpod: ^3.2.1
  flutter_riverpod: ^3.2.1
  riverpod_annotation: ^4.0.2
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  dio: ^5.7.0
  go_router: ^17.1.0
  shared_preferences: ^2.3.4
  objectbox: ^5.2.0
  objectbox_flutter_libs: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.13
  freezed: ^3.2.5
  json_serializable: ^6.8.0
  riverpod_generator: ^4.0.3
  objectbox_generator: ^5.2.0
  mocktail: ^1.0.4
  alchemist: ^0.13.0

flutter:
  uses-material-design: true
